### ISSUE TITLE
Fonts missing? Incorrect plotting of png file.

### ISSUE THREAD

**Issue by tstokowy** [dariober/cnv_facets#38]
Hi, I test CNV_Facets with exome data and get squares instead of letters on png file. I tried different versions of the container, getting the same result. Do you have any suggestions?
![JTT_JTB_facets cnv](https://user-images.githubusercontent.com/16382685/120086527-e6f52e80-c0df-11eb-9fa8-a716e403c3c0.png)

**Comment by dariober** [comment]
Hi- Can you post more details about the command line you used, the input data, and the messages you get from cnv_facets?

**Comment by tstokowy** [comment]
Hi, I use docker container (the tool is very useful for our projects!). It seems that id does not include proper fonts for plotting of png files in the container. Apparently, the pdf files are generated correctly, see attached spider plot. Maybe it would make sense to save cnv.png plot as pdf as well?
[JTT_JTB_facets.spider.pdf](https://github.com/dariober/cnv_facets/files/6569296/JTT_JTB_facets.spider.pdf)

docker run --rm -v /home/tstokowy/Data/SB2021B01exome/Alignments_210520/:/Input -v /home/tstokowy/Data/SB2021B01exome/CNV_210526/:/Output quay.io/biocontainers/cnv_facets:0.16.0--py38r36h4b26f60_1 cnv_facets.R -t /Input/JTT_exome.bam -n /Input/JTB_exome.bam -vcf /Output/00-common_all_chr.vcf.gz -o /Output/JTT_JTB_facets

**Comment by laurabuggiotti** [comment]
Hi, Im having the same issue, in lacking the headers and having squares instead of letters.
Here is how I used it:
`singularity exec --bind /camp:/mnt $bin/cnv_facets_0.16.0--py38.sif cnv_facets.R -t  $tumor/$bam -n $normal/B1d1.SM.bam  -vcf $vcf_snp --targets $panel -o $out_prefix` 
I would greatly appreciate if you could help.
Thanks

**Comment by tstokowy** [comment]
Hi I managed to solve this by mounting /usr/share/fonts/ : /usr/share/fonts (I use Docker). It took quite some time to find this solution...

**Comment by dariober** [comment]
@tstokowy Thanks for reporting back!

**Comment by reipatho** [comment]
Hi,
I encountered same problem

sudo docker run -it --rm -v '/home/reipatho/test':'/home/reipatho/test' --work-dir '/home/reipatho/test' aee69fcb43ef (cnv_facets:0.16.0)

It generated □□ fonts only .cnv.png
and I tried following command according to your advice

sudo docker run -it --rm -v '/usr/share/fonts':'/usr/share/fonts' --work-dir '/home/reipatho/test' aee69fcb43ef (cnv_facets:0.16.0)

however, 'ls' replied 'empty'
What should I do ??

Best regards

**Comment by reipatho** [comment]
Now I could install by

sudo docker pull blcdsdockerregistry/cnv_facets:0.16.0
mamba install -c bioconnda cnv_facets

Both ran succesfully without font error

Thanks!

**Comment by stianlagstad** [comment]
This is still an issue with the docker image `quay.io/biocontainers/cnv_facets:0.16.0--py38r36h4b26f60_1`. Could this issue be re-opened?

**Comment by stianlagstad** [comment]
I would like to contribute to fixing this, but it is not obvious to me how to build the docker images for bioconda recipes. I believe that the recipe for cnv_facets is this: https://oncoimmunity.slack.com/archives/C20QXFPEZ/p1712044847430729, but how exactly can I build the docker image for that locally so that I can test whether my attempted fix is working? Do I have to use this: https://github.com/bioconda/bioconda-recipes/blob/master/.github/workflows/master.yml#L66 ?

**Comment by dariober** [comment]
@stianlagstad Thanks a lot for looking into this!

> it is not obvious to me how to build the docker images for bioconda recipes

I'm afraid I cannot help here. In the past I only submitted the conda recipe (i.e. https://github.com/bioconda/bioconda-recipes/tree/master/recipes/cnv_facets) and let bioconda do the rest.

**Comment by stianlagstad** [comment]
It looks like the recipe for cnv_facets is currently blacklisted: https://github.com/bioconda/bioconda-recipes/blame/95273baa450da38a51a8ca6e307e21ffef403e2b/build-fail-blacklist#L685.

I am not able to build the recipe myself either. I cannot put more time into this right now, but in case it helps anyone else here it how it fails on my machine:
```
$ bioconda-utils build recipes --packages cnv_facets

...

13:01:40 BIOCONDA INFO (OUT) > install.packages(c("argparse"), lib= NULL, repos= "https://cran.r-project.org")
13:01:40 BIOCONDA INFO (OUT) >
13:01:40 BIOCONDA INFO (OUT) >
13:01:47 BIOCONDA ERROR COMMAND FAILED (exited with 1): /home/stian/miniconda3/envs/bioconda-build/bin/conda mambabuild --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /home/stian/miniconda3/envs/bioconda-build/conda_build_config.yaml -e /home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/cnv_facets/meta.yaml

13:01:47 BIOCONDA ERROR BUILD FAILED recipes/cnv_facets
13:01:47 BIOCONDA INFO (COMMAND) conda build purge
13:01:48 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
13:01:48 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/cnv_facets
```

Trying to execute that command (`/home/stian/miniconda3/envs/bioconda-build/bin/conda mambabuild --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /home/stian/miniconda3/envs/bioconda-build/conda_build_config.yaml -e /home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/cnv_facets/meta.yaml`) directly gives more info:
```
...

** testing if installed package keeps a record of temporary installation path
* DONE (argparse)

The downloaded source packages are in
        ‘/tmp/RtmpFu4ldW/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
>
>
Error in makeCluster(nprocs, type = "FORK") :
  could not find function "makeCluster"
Calls: exec_snp_pileup_parallel
Execution halted
Traceback (most recent call last):
  File "/home/stian/miniconda3/envs/bioconda-build/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/build.py", line 2198, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/utils.py", line 451, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/stian/miniconda3/envs/bioconda-build/conda-bld/cnv_facets_1712058326761/work/conda_build.sh']' returned non-zero exit status 1.
``jii

**Comment by stianlagstad** [comment]
I posted an issue on the bioconda repo about this: https://github.com/bioconda/bioconda-recipes/issues/469
